### ISSUE TITLE
如何设置起始刻度

### ISSUE THREAD

**Issue by RommelLiang** [LichFaker/ScaleView#1]
请问，如何设置让刻度默认指向某一刻度？

**Comment by LichFaker** [comment]
默认指向的刻度指针是居中`View`的，该刻度值受`scale_view_min`、`scale_view_margin`、`layout_width`影响；你也可以通过`scroll`方法滑动相应刻度来指向某一刻度

**Comment by RommelLiang** [comment]
哦哦！我想做到在Activity启动的时候让刻度指向特定数值，我该怎么做呢？

**Comment by LichFaker** [comment]
@RommelLiang  现在启动的时候就是指向一个数值的， 可能不是你想要的。可以按照上面讲的思路自己尝试下就好了，建议通过scroll的方式

**Comment by RommelLiang** [comment]
嗯嗯，谢谢！这个东西真是帮了我大忙了 @LichFaker

**Comment by LichFaker** [comment]
@RommelLiang 应该的， 不用谢
