### ISSUE TITLE
如何做到用户设置一个值、刻度尺正确显示

### ISSUE THREAD

**Issue by Boom618** [LichFaker/ScaleView#2]
TextView 换成 EditView

**Comment by LichFaker** [comment]
暂时还不支持，可以通过当前刻度和刻度间隔来计算滑动数值；如果不急，今晚我可以更新下

**Comment by DuoLa512** [comment]
大佬，那个Textview换成EditView，可以输入数值，滚动到固定的值的功能可以了吗？方便的话，发个demo给我，谢谢

**Comment by LichFaker** [comment]
@DuoLa512  demo中应该有， 调`setCurScale `即可
